Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "web-server"
    vb.memory = "512"
  end
  config.vm.provision :puppet do |puppet|
    puppet.options = ["--user", "root"]
    puppet.manifests_path = ""
    puppet.manifest_file = "init.pp"
  end
end
